name: Log API_URL Secret

on:
    push:
        branches:
            - '**'

jobs:
    log_secret:
        environment: development
        runs-on: ubuntu-latest
        steps:
            - name: Log API_URL
              env:
                  API_URL: ${{ secrets.API_URL }}
              run: |
                  echo "API_URL: $API_URL"
